### ISSUE TITLE
Input with strip=True will error when user presses the down arrow

### ISSUE THREAD

**Issue by lxylxy123456** [Mckinsey666/bullet#85]
I am working on MacOS. I have installed bullet 2.2.0 using pip.
When I running the following code, and press the down arrow,
```py
from bullet import Input
cli = Input('Press down arrow: ', strip=True)
result = cli.launch()
```
 I see error:
```
% python3 /tmp/a.py
Press down arrow: Traceback (most recent call last):
  File "/tmp/a.py", line 3, in <module>
    result = cli.launch()
  File "/usr/local/lib/python3.9/site-packages/bullet/client.py", line 458, in launch
    return result.strip() if self.strip else result
AttributeError: 'NoneType' object has no attribute 'strip'
% 
```
This error does not happen when `strip=False`

**Comment by h4rldev** [comment]
That is because when you run the program it listens for input, And due to how bullet works, It will make that input be None
Because it uses variables to store input data. And due to the down and up arrow being used for bullet.Bullet

**Comment by danner26** [comment]
Hello, my colleague and I use this codebase pretty often in our projects but the original and all forks seem to be stale. We have thus forked into our own project, [BulletPrompt](https://github.com/danner26/BulletPrompt).

I have taken the liberty to fix this issue, which will be available in the next release.

PR with fix: https://github.com/danner26/BulletPrompt/pull/11
Release Version: v2.2.2
